(function(app, $, ko) {

	var viewModel = {
		autocompleteOptions: ko.observableArray(["New York, New York",
"Los Angeles, California",
"Chicago, Illinois",
"Houston, Texas",
"Phoenix, Arizona",
"Philadelphia, Pennsylvania",
"San Antonio, Texas",
"San Diego, California",
"Dallas, Texas",
"San Jose, California",
"Detroit, Michigan",
"San Francisco, California",
"Jacksonville, Florida",
"Indianapolis, Indiana",
"Austin, Texas",
"Columbus, Ohio",
"Fort Worth, Texas",
"Charlotte, North Carolina",
"Memphis, Tennessee",
"Boston, Massachusetts",
"Baltimore, Maryland",
"El Paso, Texas",
"Seattle, Washington",
"Denver, Colorado",
"Nashville-Davidson, Tennessee",
"Milwaukee, Wisconsin",
"Washington, District of Columbia",
"Las Vegas, Nevada",
"Louisville/Jefferson County, Kentucky",
"Portland, Oregon",
"Oklahoma City, Oklahoma",
"Tucson, Arizona",
"Atlanta, Georgia",
"Albuquerque, New Mexico",
"Kansas City, Missouri",
"Fresno, California",
"Mesa, Arizona",
"Sacramento, California",
"Long Beach, California",
"Omaha, Nebraska",
"Virginia Beach, Virginia",
"Miami, Florida",
"Cleveland, Ohio",
"Oakland, California",
"Raleigh, North Carolina",
"Colorado Springs, Colorado",
"Tulsa, Oklahoma",
"Minneapolis, Minnesota",
"Arlington, Texas",
"Honolulu, Hawaii",
"Wichita, Kansas",
"St. Louis, Missouri",
"New Orleans, Louisiana",
"Tampa, Florida",
"Santa Ana, California",
"Anaheim, California",
"Cincinnati, Ohio",
"Bakersfield, California",
"Aurora, Colorado",
"Toledo, Ohio",
"Pittsburgh, Pennsylvania",
"Riverside, California",
"Lexington-Fayette, Kentucky",
"Stockton, California",
"Corpus Christi, Texas",
"Anchorage, Alaska",
"St. Paul, Minnesota",
"Newark, New Jersey",
"Plano, Texas",
"Buffalo, New York",
"Henderson, Nevada",
"Fort Wayne, Indiana",
"Greensboro, North Carolina",
"Lincoln, Nebraska",
"Glendale, Arizona",
"Chandler, Arizona",
"St. Petersburg, Florida",
"Jersey City, New Jersey",
"Scottsdale, Arizona",
"Orlando, Florida",
"Madison, Wisconsin",
"Norfolk, Virginia",
"Birmingham, Alabama",
"Winston-Salem, North Carolina",
"Durham, North Carolina",
"Laredo, Texas",
"Lubbock, Texas",
"Baton Rouge, Louisiana",
"North Las Vegas, Nevada",
"Chula Vista, California",
"Chesapeake, Virginia",
"Gilbert, Arizona",
"Garland, Texas",
"Reno, Nevada",
"Hialeah, Florida",
"Arlington, Virginia",
"Irvine, California",
"Rochester, New York",
"Akron, Ohio",
"Boise City, Idaho",
"Irving, Texas",
"Fremont, California",
"Richmond, Virginia",
"Spokane, Washington",
"Modesto, California",
"Montgomery, Alabama",
"Yonkers, New York",
"Des Moines, Iowa",
"Tacoma, Washington",
"Shreveport, Louisiana",
"San Bernardino, California",
"Fayetteville, North Carolina",
"Glendale, California",
"Augusta-Richmond County, Georgia",
"Grand Rapids, Michigan",
"Huntington Beach, California",
"Mobile, Alabama",
"Newport News, Virginia",
"Little Rock, Arkansas",
"Moreno Valley, California",
"Columbus, Georgia",
"Amarillo, Texas",
"Fontana, California",
"Oxnard, California",
"Knoxville, Tennessee",
"Fort Lauderdale, Florida",
"Salt Lake City, Utah",
"Worcester, Massachusetts",
"Huntsville, Alabama",
"Tempe, Arizona",
"Brownsville, Texas",
"Jackson, Mississippi",
"Overland Park, Kansas",
"Aurora, Illinois",
"Oceanside, California",
"Tallahassee, Florida",
"Providence, Rhode Island",
"Rancho Cucamonga, California",
"Ontario, California",
"Chattanooga, Tennessee",
"Santa Clarita, California",
"Garden Grove, California",
"Vancouver, Washington",
"Grand Prairie, Texas",
"Peoria, Arizona",
"Sioux Falls, South Dakota",
"Springfield, Missouri",
"Santa Rosa, California",
"Rockford, Illinois",
"Springfield, Massachusetts",
"Salem, Oregon",
"Port St. Lucie, Florida",
"Cape Coral, Florida",
"Dayton, Ohio",
"Eugene, Oregon",
"Pomona, California",
"Corona, California",
"Alexandria, Virginia",
"Joliet, Illinois",
"Pembroke Pines, Florida",
"Paterson, New Jersey",
"Pasadena, Texas",
"Lancaster, California",
"Hayward, California",
"Salinas, California",
"Hampton, Virginia",
"Palmdale, California",
"Pasadena, California",
"Naperville, Illinois",
"Kansas City, Kansas",
"Hollywood, Florida",
"Lakewood, Colorado",
"Torrance, California",
"Escondido, California",
"Fort Collins, Colorado",
"Syracuse, New York",
"Bridgeport, Connecticut",
"Orange, California",
"Cary, North Carolina",
"Elk Grove, California",
"Savannah, Georgia",
"Sunnyvale, California",
"Warren, Michigan",
"Mesquite, Texas",
"Fullerton, California",
"McAllen, Texas",
"Columbia, South Carolina",
"Carrollton, Texas",
"Cedar Rapids, Iowa",
"McKinney, Texas",
"Sterling Heights, Michigan",
"Bellevue, Washington",
"Coral Springs, Florida",
"Waco, Texas",
"Elizabeth, New Jersey",
"West Valley City, Utah",
"Clarksville, Tennessee",
"Topeka, Kansas",
"Hartford, Connecticut",
"Thousand Oaks, California",
"New Haven, Connecticut",
"Denton, Texas",
"Concord, California",
"Visalia, California",
"Olathe, Kansas",
"El Monte, California",
"Independence, Missouri",
"Stamford, Connecticut",
"Simi Valley, California",
"Provo, Utah",
"Killeen, Texas",
"Springfield, Illinois",
"Thornton, Colorado",
"Abilene, Texas",
"Gainesville, Florida",
"Evansville, Indiana",
"Roseville, California",
"Charleston, South Carolina",
"Peoria, Illinois",
"Athens-Clarke County, Georgia",
"Lafayette, Louisiana",
"Vallejo, California",
"Lansing, Michigan",
"Ann Arbor, Michigan",
"Inglewood, California",
"Santa Clara, California",
"Flint, Michigan",
"Victorville, California",
"Costa Mesa, California",
"Beaumont, Texas",
"Miami Gardens, Florida",
"Manchester, New Hampshire",
"Westminster, Colorado",
"Miramar, Florida",
"Norman, Oklahoma",
"Cambridge, Massachusetts",
"Midland, Texas",
"Arvada, Colorado",
"Allentown, Pennsylvania",
"Elgin, Illinois",
"Waterbury, Connecticut",
"Downey, California",
"Clearwater, Florida",
"Billings, Montana",
"West Covina, California",
"Round Rock, Texas",
"Murfreesboro, Tennessee",
"Lewisville, Texas",
"West Jordan, Utah",
"Pueblo, Colorado",
"San Buenaventura (Ventura), California",
"Lowell, Massachusetts",
"South Bend, Indiana",
"Fairfield, California",
"Erie, Pennsylvania",
"Rochester, Minnesota",
"High Point, North Carolina",
"Richardson, Texas",
"Richmond, California",
"Burbank, California",
"Berkeley, California",
"Pompano Beach, Florida",
"Norwalk, California",
"Frisco, Texas",
"Columbia, Missouri",
"Gresham, Oregon",
"Daly City, California",
"Green Bay, Wisconsin",
"Wilmington, North Carolina",
"Davenport, Iowa",
"Wichita Falls, Texas",
"Antioch, California",
"Palm Bay, Florida",
"Odessa, Texas",
"Centennial, Colorado",
"Boulder, Colorado",
"West Palm Beach, Florida",
"Everett, Washington",
"Portsmouth, Virginia",
"Temecula, California",
"Tyler, Texas",
"Rialto, California",
"Carlsbad, California",
"Kenosha, Wisconsin",
"Murrieta, California",
"North Charleston, South Carolina",
"Sandy, Utah",
"South Gate, California",
"Gary, Indiana",
"Fargo, North Dakota",
"Hillsboro, Oregon",
"Orem, Utah",
"Surprise, Arizona",
"Broken Arrow, Oklahoma",
"Mission Viejo, California",
"Roanoke, Virginia",
"El Cajon, California",
"Compton, California",
"Albany, New York",
"Lakeland, Florida",
"Brockton, Massachusetts",
"Las Cruces, New Mexico",
"Beaverton, Oregon",
"Clovis, California",
"Tuscaloosa, Alabama",
"San Mateo, California",
"Greeley, Colorado",
"Macon, Georgia",
"Vista, California",
"Carson, California",
"San Angelo, Texas",
"Lawrence, Kansas",
"Vacaville, California",
"Davie, Florida",
"Lawton, Oklahoma",
"Yuma, Arizona"]),
		autocompleteValue: ko.observable(),

		windowOpen: ko.observable(),

		startDate: ko.observable(new Date())
	};
	
	$(document).ready(function() {
		ko.applyBindings(viewModel);
	});

})(window.app = window.app || {}, jQuery, ko);